const booksData = [
    {
        id: 1,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publishedYear: "1960",
        image: "https://m.media-amazon.com/images/I/81gepf1eMqL._SY522_.jpg",
        category: "Fiction",
        rating: 2.5,
        description: "To Kill a Mockingbird is a coming-of-age story, an anti-racist novel. The book by H Lee",
    },
    {
        id: 2,
        title: "1984",
        author: "George Orwell",
        publishedYear: "1949",
        image: "https://m.media-amazon.com/images/I/91qK2DSAXSL._SY425_.jpg",
        category: "Science Fiction",
        rating: 4.6,
        description: "1984: A Novel, unleashes a unique plot as per which No One is Safe or Free.",
        
    },
    {
        id: 3,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        publishedYear: "1813",
        image: "https://m.media-amazon.com/images/I/712P0p5cXIL._AC_UF1000,1000_QL80_.jpg",
        category: "Romance",
        rating: 3.5,
        description: "A romantic novel that explores themes of class, marriage, and morality in 19th century England.",
    },
    {
        id: 4,
        title: "The Chronicles Of Narnia Box Set",
        author: "C.S.Lewis",
        publishedYear: "1948",
        image: "https://m.media-amazon.com/images/I/71PZgfCpS5L._SL1500_.jpg",
        category: "Fantasy",
        rating: 4.2,
        description: "The Chronicles of Narnia have enchanted millions of readers for over seventy years and the magical events",
    },
    {
        id: 5,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        publishedYear: "1951",
        image: "https://m.media-amazon.com/images/I/7108sdEUEGL._SY522_.jpg",
        category: "Fiction",
        rating: 2.8,
        description: "The Catcher in Rye is the ultimate novel for disaffected youth, but it's relevant to all ages.",
    },
    {
        id: 6,
        title: "Brave New World",
        author: "Aldous Huxley",
        publishedYear: "1932",
        image: "https://m.media-amazon.com/images/I/91D4YvdC0dL._SY466_.jpg",
        category: "Science Fiction",
        rating: 4.9,
        description: "The book begins with a lengthy introduction, how he thinks the entire world will function in the far future",
    },
    {
        id: 7,
        title: "Jail Diary",
        author: "Bhagat Singh",
        publishedYear: "1929",
        image: "https://m.media-amazon.com/images/I/71hb6akJwYL._SY466_.jpg",
        category: "Historic",
        rating: 5,
        description: "A portrait of man with an acute scholarly mind and a cheerful socialist heart.",
    },
    {
        id: 8,
        title: "The Canterville Ghost",
        author: "Oscar Wilde",
        publishedYear: "1887",
        image: "https://m.media-amazon.com/images/I/713-hV5Oz8L._SY342_.jpg",
        category: "Horror",
        rating: 4.2,
        description: "The story follows the Otis family as they move into Canterville Chase, a haunted mansion in England.",
    },
    {
        id: 9,
        title: "Ugly Love",
        author: "Colleen Hoover",
        publishedYear: "2015",
        image: "https://m.media-amazon.com/images/I/71E8VNPC1dL._SY466_.jpg",
        category: "Romance",
        rating: 4.4,
        description: "A heart-wrenching love story that proves attraction at first sight can be messy.",
    },
    {
        id: 10,
        title: "Chamber of Secrets",
        author: "J.K. Rowling",
        publishedYear: "1998",
        image: "https://m.media-amazon.com/images/I/818umIdoruL._SY466_.jpg",
        category: "Fantasy",
        rating: 4.7,
        description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby.",
    },
    {
        id: 11,
        title: "Never Lie",
        author: "Freida McFadden",
        publishedYear: "2022",
        image: "https://m.media-amazon.com/images/I/81+ceFx9BcL._SY466_.jpg",
        category: "Science Fiction",
        rating: 4.3,
        description: "When a violent winter storm traps them at the estate, the house begins to lose its appeal.",
    },
    {
        id: 12,
        title: "Guns of August",
        author: "Barbara W. Tuchman",
        publishedYear: "1962",
        image: "https://m.media-amazon.com/images/I/71vkxIftlzL._SY522_.jpg",
        category: "Historic",
        rating: 4.6,
        description: "A brilliant piece of military history which proves up to the hilt the force. The Military Force.",
    },
    {
        id: 13,
        title: "Streetlight People",
        author: "Charlene Thomas",
        publishedYear: "2024",
        image: "https://m.media-amazon.com/images/I/91j-EeAs3tL._SY466_.jpg",
        category: "Horror",
        rating: 3.9,
        description: "Streetlight is a dot on the map you pass on your way to somewhere else. The book by C Thomas.",
    },
    {
        id: 14,
        title: "The Mirror",
        author: "Nora Roberts",
        publishedYear: "2024",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1709902335i/203578918.jpg",
        category: "Fiction",
        rating: 4,
        description: "Then one night the mirror appears and Sonya glides through this looking glass.",
    },
    {
        id: 15,
        title: "A History of India",
        author: "Romila Thapar",
        publishedYear: "1966",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388470854i/276113.jpg",
        category: "Historic",
        rating: 3.6,
        description: "A full account of Indian history from the establishment of Aryan culture to the coming of the Mughals.",
    },
    {
        id: 16,
        title: "Summit’s Edge",
        author: "Sara Driscoll",
        publishedYear: "2024",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1709958320i/209194445.jpg",
        category: "Adventure",
        rating: 4.5,
        description: "As long as there hope of finding life, no mission is too dangerous for Meg Jennings.",
    },
];

export default booksData;